DRIVER_PATH = "C:\SeleniumDrivers"
URL = "https://vast.gg/gaming-pc-giveaway/rosel-starforge-systems-4399-rtx-4090-gaming-pc-giveaway-dec-23rd-jan-22nd/?utm_campaign=Vast%20Campaign%20Alerts&utm_medium=email&utm_source=Revue%20newsletter"
FIRST_NAME = "Ethan"
LAST_NAME = "Machleder"
EMAIL = "etanm2013@gmail.com"